services:

  web-demo:
    # 当前目录下的Dockerfile构建
    build: .
    ports:
      - '8080:8080'
    volumes:
      - web-demo-data:/usr/local/workspace/web-demo
    environment:
      - TZ=Asia/Shanghai

  redis:
    image: 'redis:latest'
    volumes:
      - redis-data:/data
    environment:
      - TZ=Asia/Shanghai

volumes:
  web-demo-data:
  redis-data: